version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "prof_iu"
      POSTGRES_USER: "predsed"
      POSTGRES_PASSWORD: "predsed_profa_iu_3301"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../init_db/:/docker-entrypoint-initdb.d
      - prof_iu-data:/home/golgofa/'Документы'/university/prof_iu_bot/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U predsed -d prof_iu"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "polina.tikunowa@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "1love3000porf_iu"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/home/golgofa/'Документы'/university/prof_iu_bot/pg_admin/data
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  prof_iu-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
